### PR TITLE
[B] Footer text nav has incorrect top margin

### PR DESCRIPTION
**Pull request by naomiyaki**
Only show Page records in footer if they have the attribute `show_in_footer`

### CODE REVIEW

**Comment by zdavis** [comment]
Needs tests; ZD to provide.

**Comment by zdavis** [comment]
Hey @SMaxOwok could you please add a test for this that asserts that only pages with a true show_in_footer attribute appear in the footer? I thought I'd get to it last week, but ran out of time.

**Comment by zdavis** [comment]
Hey Max, sorry I didn't catch this earlier — we need to make one more change here. There's a hard coded ULR in the component, which needs to be refactored to use the new link helpers. Could you update this PR to use the link helpers. Note that in doing so, we'll need the PR to be against master, not v0.1.x, which I think is fine.

**Comment by SMaxOwok** [comment]
Rebased on master and updated to use link helper.

**Pull request merged**
