### PR TITLE
 [F] Add roles and permissions framework; add project logs

### LINKED ISSUE #789: Implement author dashboard
Placeholder for now; description TBD.

### PR DESCRIPTION
**Pull request by SMaxOwok**
Advances #789 

Based on `mo/791`/#816

### CODE REVIEW

**Comment by zdavis** [comment]
As an owner of a project:

image

**Comment by zdavis** [comment]
This is looking close, although it seems to me that neither authors nor owners have permission to modify anything.

**Comment by SMaxOwok** [comment]
This branch is primarily just creating the separate dashboard and adjusting the UI on the admin dash. 
 Generally I haven't adjusted the authorizers in this branch, except for projects. 

I'm setting the actual permissions for user roles in `mo/403` where I'm also limiting project item visibility.  Let me know if you want me to take a pass back over this branch and put the updated authorizer logic here instead.

**Comment by zdavis** [comment]
Nah, it's fine to have them be separate.

**Comment by zdavis** [comment]
- [ ] Looks like there's a loop in Backend Navigation.Secondary that's missing a key. I see an error to this effect in my console at `/backend/people`

**Pull request merged**
