### PR TITLE
[B] Improve open graph meta tags

### LINKED ISSUE #1518: Homepage opengraph tags are not referencing settings
We aren't using the values in settings at the top level (home and following are what I've seen so far).

### PR DESCRIPTION
**Pull request by SMaxOwok**
Fixes #1518

### CODE REVIEW

**Comment by zdavis** [comment]
Max is going to address og:site_name and add default description meta tag field, then this is ready to accept.

**Comment by SMaxOwok** [comment]
Ok, I've addressed the notes you mentioned above, but also several other things that I think were missing.  I added in the Twitter site name based on a top-level Twitter account being set and also the top-level installation logo.

Getting these fallback values to cascade the correct way involved a little refactoring to `HeadContent`, so please review as if this was a new PR.  Do you see any ways that component could be made a little cleaner?

**Comment by zdavis** [comment]
Seems to me that fatal error shouldn't be imported here.

**Comment by SMaxOwok** [comment]
Rebased on `v2.0.x` to remove `FatalError` import.

**Pull request merged**
