### PR TITLE
[B] Highlight "learn more..." in reader menu

### LINKED ISSUE #596: Weird link hover state in reader about
Shouldn't "Learn more about" share the hover state?

image

### PR DESCRIPTION
**Pull request by naomiyaki**
Closes #596

### CODE REVIEW

**Comment by zdavis** [comment]
Not quite there yet — I went back to the comp:

image

Let's expand this to make the hover states look like they do in the comp for each item in that nav.

**Comment by zdavis** [comment]
Ping @naomiyaki — let me know when you think you can get to this, and what remains on this PR please.

**Comment by zdavis** [comment]
Hey @SMaxOwok I can't seem to get @naomiyaki's attention on this. Could you pull this PR and see if does what it's supposed to?

**Comment by naomiyaki** [comment]
@zdavis I've double checked this menu against the comps and pushed with some minor updates/rebase, and I believe this commit is now ready! Please let me know if you want any further changes to the menu.

**Comment by zdavis** [comment]
Terrific. I will review it this afternoon/evening. Thanks.

**Comment by zdavis** [comment]
Looks great. Thanks!

**Pull request merged**
