### PR TITLE
[F] Refactor and improve full text search

### LINKED ISSUE #1997: Address inefficiencies in indexing searchable nodes
On the CUNY instance, reindexing searchable nodes takes quite a long time and makes load spike considerably. These requests need to be batched for better performance.

### LINKED ISSUE #2025: Proptype error on mobile search input
```
Warning: `value` prop on `input` should not be null. Consider using an empty string to clear the component or `undefined` for uncontrolled components.
```

### PR DESCRIPTION
**Pull request by zdavis**
Fixes #2025. Fixes #1997.

### CODE REVIEW

**Comment by zdavis** [comment]
@SMaxOwok this is ready for testing. I still want to clean up a few things and fix up the new avatar icon, and there's a failing test I need to look at, but I think the fundamentals are in place. Please pull it tomorrow and put it through the paces. Be sure to test both the reader and the frontend search, as well as various places in the backend (record lists) where ES is utilized. I will test further as well—hopefully we can get this out the door by EOD tomorrow.

You will need to reindex all the things.

**Comment by zdavis** [comment]
Note to self... check #2038.

**Comment by zdavis** [comment]
Check #2033 as well.

**Comment by SMaxOwok** [comment]
Just need to tweak reader overlay scroll to result.  Otherwise this has been looking good.

**Pull request merged**
