### PR TITLE
[B] Update mobile styles on avatar picker

### LINKED ISSUE #590: Cover picker is a bit too crowded on iPhone 4/5 size
screen shot 2017-09-14 at 1 32 22 pm

### PR DESCRIPTION
**Pull request by naomiyaki**
Closes #590

### CODE REVIEW

**Comment by naomiyaki** [comment]
@zdavis this fixes the mobile issues on this component. I hadn't worked on this component before, but due to its touching file/image uploads it has a number of overrides that say bad CSS override/abstraction smell to me. Is it OK if I add a 0.4 issue to refactor this?

**Comment by zdavis** [comment]
I'd prefer you go ahead and refactor it now rather than postpone it until 0.4. I find that those kind of future refactors are likely to not happen.

**Comment by naomiyaki** [comment]
OK, I'll do that in this PR once I've gone through the rest of the small changes. Just want to make sure everything is functionally ready for your launch.

**Comment by naomiyaki** [comment]
@zdavis I've force pushed a number of changes that refactor out extraneous styles and overrides, in addition to a bunch of small changes that make this component match the comps typography/positioning more closely. Please QA and feel free to merge when ready!

**Comment by zdavis** [comment]
Mobile doesn't render correctly with generic thumbnail:
image

**Comment by zdavis** [comment]
Alignment of generic thumbnail is off in desktop view as well:

image

This interface also seems really huge now. Maybe that's how it is in the comp though? Can you confirm that the sizing is correct?

**Comment by naomiyaki** [comment]
@zdavis I've updated a number of things on this component:
- Fix regression (noted above)
- Updated text sizing inside Form.Upload to match comps
- Added hover states for underlined links in Form.Upload
- Added SVG to match cover placeholder 
- Implemented SVG placeholder based on prop

Please have a look. I don't know if you'll be able to review before next week, but hopefully everything works as intended or is simple enough to adjust!

**Comment by zdavis** [comment]
The fonts don't match. In the screenshot below, we have sans-serif on the left and sofia on the right. I didn't compare to comps, but I assume that's not intentional.

image

**Comment by zdavis** [comment]
Looks great! Thanks!

**Pull request merged**
