### PR TITLE
[F] Refactor resource tag list into component

### PR DESCRIPTION
**Pull request by SMaxOwok**
[Delivers #143205011]

### CODE REVIEW

**Comment by zdavis** [comment]
I'm seeing a couple problems right off the bat...

- No hover state on the tags
- Clicking a tag should filter the list by that tag (the tag could be a link, since filters can be set via URL)
- If the resource has too many tags, they don't display at all.

**Comment by SMaxOwok** [comment]
@zdavis, I removed the hover states and and links on purpose because there are the tag filters on the view.  The comps also don't show them as links.  Just want to confirm that the desired behavior is for them to link as well before I add that back.

**Comment by SMaxOwok** [comment]
@zdavis rebased this on master

**Comment by zdavis** [comment]
Rebased on master!

**Pull request merged**
