### PR TITLE
[F] List all highlights and annotations for a given text

### PR DESCRIPTION
**Pull request by SMaxOwok**
[Completes #450]

### CODE REVIEW

**Comment by zdavis** [comment]
Rebased onto master

**Comment by zdavis** [comment]
Good start... some changes:

1. Expose this at /read/:text_id/my/annotations in the client.
2. The API route should be at /api/v1/me/relationships/annotations?filter[text]=:text_uuid

The client doesn't have to pass the users UUID to the API, since all the routes under api/v1/me are understood to operate on the current_user

It would be nice if we could keep this more in line with the reader UI. You have it in a very wide container, and none of the reading controls work. How does it look if the width is constrained like it is when reading a text_section?

I also think we need some kind of header here. And the green is too much — need a paler green or a gray. We can get design from Lael, but something to consider.

**Comment by SMaxOwok** [comment]
@zdavis I changed up the routes and added the reader control functionality (moved into helper).  I added some basic dark scheme styles as well, I'm not sure how full-on you want to go with them.  The annotation drawer that this is styled after has no dark scheme in the reader, right now.  The components respond to all the controls with the exception of font-size on the annotated passage.  

annotations

Additionally, I added a button to the annotations in the reader menu.  I'm not sure if it's best there or somewhere in the actual reader as a button, but would be easily moved elsewhere.

screen shot 2017-07-26 at 2 10 31 pm

So far everything that is in place should be easy to move around or change, so let me know what you think as your thoughts on this develop.

**Comment by zdavis** [comment]
Resolving this conflict requires a little discussion. @SMaxOwok and @naomiyaki let's touch base tomorrow morning. Max has moved a bunch of styles out of the Text component, but I don't think that makes sense now that we're moving this into a modal. Meanwhile, I've made changes recently around how classes are set in relation to the reader font size that conflicts with the direction Max is going in.

**Comment by zdavis** [comment]
I'm closing this PR in favor of a different branch that reuses existing components.

**Pull request closed without merging**
