### PR TITLE
Update text list button/table styles for mobile

### PR DESCRIPTION
**Pull request by naomiyaki**
Note that this PR is blocked as its dependent on new button styles in #619. Once that PR is accepted, this one can be QA'd (by Naomi), rebased, and then released for review.

### CODE REVIEW

**Comment by zdavis** [comment]
@naomiyaki #619 has been merged, per your comment above, and I've removed the blocked label. There is a conflict, however, which needs to be resolved. Please address, review, and let me know when this is ready.

**Comment by naomiyaki** [comment]
@zdavis Merge conflict fixed and styles updated a teensy bit based on merged styles from #619

**Comment by zdavis** [comment]
Accepting this for now. I think we need take another pass at this in the future, as the layout still doesn't feel right. That said, it's much better than it was — doesn't feel broken any more. Thanks.

**Comment by zdavis** [comment]
For posterity, this is where we landed:

image

**Pull request merged**
