### PR TITLE
[F] Improve project exports

### PR DESCRIPTION
**Pull request by zdavis**

### CODE REVIEW

**Comment by zdavis** [comment]
@scryptmouse please make sure tests pass here so this can be accepted.

**Comment by zdavis** [comment]
Hey @scryptmouse, could you please rebase this on master? Thanks.

**Comment by scryptmouse** [comment]
I rebased on origin/master, but it's still showing conflicts here for `client/dist/manifold/manifest.json` and `client/dist/manifold/ssr/manifold-client-ssr.js`. Are those managed by something else? They don't show up as a conflict to address when rebasing locally.

**Comment by zdavis** [comment]
No problem. I can just accept it locally.

**Comment by zdavis** [comment]
This PR base branch was set to v5.x, but we can put it in Master I think.

**Comment by scryptmouse** [comment]
Oh, of course. That's why rebasing didn't fix those conflicts.

**Pull request merged**
