### PR TITLE
[F] Implement comments on resource detail

### PR DESCRIPTION
**Pull request by SMaxOwok**
[Completes #271]

### CODE REVIEW

**Comment by zdavis** [comment]
Please include screenshots of what this looks like so I that I can provide design and layout feedback without having to set it up in my environment

**Comment by SMaxOwok** [comment]
fireshot capture 3 - manifold scholarship_ - http___manifold dev_browse_project_
screen shot 2017-04-27 at 12 21 57 pm

I tried to combine what I saw in the comps with what you had done with the comment components.

**Comment by SMaxOwok** [comment]
fireshot capture 4 - manifold scholarship_ - http___manifold dev_browse_project_

Mobile

**Comment by zdavis** [comment]
Max, can you please change this PR so it's to v0.2.0 rather than master, and also rebase it onto v0.2.0? Once that's done, I'll review.

**Pull request merged**
