### PR TITLE
[C] Update Rails to 5.2.3

### PR DESCRIPTION
**Pull request by SMaxOwok**

### CODE REVIEW

**Comment by zdavis** [comment]
Could you confirm that you ran the app:update task and went through each change it proposed carefully, and that you addressed all deprecation warnings in the log?

**Comment by SMaxOwok** [comment]
Seeing a lot of `Unable to autoload constant` and `already initialized constant Api`.  Trying to figure out why.

**Comment by SMaxOwok** [comment]
> Seeing a lot of `Unable to autoload constant` and `already initialized constant Api`. Trying to figure out why.

Seems to be related to the ruby upgrade commit, not rails.

**Comment by zdavis** [comment]
:clap:

**Pull request merged**
