### PR TITLE
[F] Add margin controls to reader

### PR DESCRIPTION
**Pull request by naomiyaki**
[FEATURE DELIVERS #111080632] New actions have been added to increment/
decrement margin values in the store, that use a now-abstracted version
of the font-size increment/decrement reducers. In the view, there are
now buttons to increase/decrease the margin size in the reader. It's
important to note that while these buttons do not have disabled states
for minimum and maximum sizes, they do stop changing the store when a
limit is reached.

### CODE REVIEW

**Comment by zdavis** [comment]
Looks like we need to adjust our Hounds SCSS rules.

Zach

**Comment by naomiyaki** [comment]
A bit! Some of these are OK, and I'd be happy to talk about setting a nesting limit if we want one, but the alphabetical order of CSS properties should probably go.

**Comment by zdavis** [comment]
You may as well add the linting config to this pull request, and also fix errors. That way we can see it pass all CI checks before merging it. Sound OK?

**Comment by zdavis** [comment]
Naomi, can you rebase this onto development and force push so we can see how it does with the new scss linting rules I just merged? Thanks!

**Comment by zdavis** [comment]
Closing in favor of #14

**Pull request closed without merging**
