### PR TITLE
[B] Remove secondary skip-to links

### LINKED ISSUE #2004: Remove nested skip-to links
This page has a second skip nav between the main content area and the banner. This deducts from the functional accessibility of the page because it adds extra tabstops for keyboard users which are not needed. As Hadi would say, this is too helpful

### PR DESCRIPTION
**Pull request by SMaxOwok**
Fixes #2004

### CODE REVIEW

**Comment by SMaxOwok** [comment]
skip

**Comment by SMaxOwok** [comment]
Adjust styles, squarer or from bottom.

**Comment by SMaxOwok** [comment]
@laelito @zdavis updated skip to nav styles

**Comment by zdavis** [comment]
I'm Ok with this. Lael, for context—this will pop up from the lower left when the user focuses on the skip nav (by pressing tab). Most users won't ever see this. For an example, go to http://www.washington.edu/ and press the tab key.

**Comment by zdavis** [comment]
Moved it back to the top left and gave it a little opacity.

**Pull request merged**
