### PR TITLE
[WIP] Document ResourceCollection API endpoints

### PR DESCRIPTION
**Pull request by ConnorChristensen**
I hit two sticking points in documenting these routes.

1. A 500 response on POST for `/resource_collections` route
2. Not knowing how to attach a `resource_collection` to a `text_section`. 

I looked around in the UI as well as the factory bot and there didn't seem to be an obvious place to attach a resource_collection to a text_section. All tests pass as is, I want to make sure that I am using the `/text_sections/{text_section_id}/relationships/resource_collections` route correctly.

I am happy to go back and fix these if you have some suggestions, or move on and leave them to you.

### CODE REVIEW

**Comment by zdavis** [comment]
> 1. A 500 response on POST for `/resource_collections` route

I'd like you point you in the right direction without having to take the time to debug this. What are you seeing in the logs when you trigger this request?

> 2. Not knowing how to attach a `resource_collection` to a `text_section`.

This route was removed in https://github.com/ManifoldScholar/manifold/commit/0408ac37b3c635237af8d33872dd58716ab5d83a#diff-cec8b31590fabd58186af04b474be177. It should not be documented.

**Comment by ConnorChristensen** [comment]
### For my first issue

I wrote a test that shows what a failing example looks like on creating a resource_collection. You can see this test if you run `rspec -fd spec/requests/resource_collections_spec.rb` from the `api` folder.

Here are the logs if they are helpful:
 
```
Started POST "/api/v1/resource_collections" for 127.0.0.1 at 2020-01-02 01:15:07 -0800
Processing by Api::V1::ResourceCollectionsController#create as */*
  Parameters: {"data"=>{"attributes"=>{"title"=>"fewafewafewa", "description"=>"fewafewafewa"}, "relationships"=>{}}}
  User Load (0.4ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = $1 LIMIT $2  [["id", "6eefc84d-b673-47cf-939f-ac17b689fa26"], ["LIMIT", 1]]
  ↳ app/controllers/concerns/authentication.rb:21
  HABTM_Roles Load (0.2ms)  SELECT "users_roles".* FROM "users_roles" WHERE "users_roles"."user_id" = $1  [["user_id", "6eefc84d-b673-47cf-939f-ac17b689fa26"]]
  ↳ app/controllers/concerns/authentication.rb:21
  Role Load (0.3ms)  SELECT "roles".* FROM "roles" WHERE "roles"."id" = $1  [["id", "b6b69413-3145-49ee-8f8c-4bbc95b8935b"]]
  ↳ app/controllers/concerns/authentication.rb:21
  Favorite Load (0.3ms)  SELECT "favorites".* FROM "favorites" WHERE "favorites"."user_id" = $1  [["user_id", "6eefc84d-b673-47cf-939f-ac17b689fa26"]]
  ↳ app/controllers/concerns/authentication.rb:21
Completed 500 Internal Server Error in 9ms (ActiveRecord: 1.2ms)
```

### For my second issue

Since my Ruby on Rails knowledge is still not that good, in order to both understand the route, and make sure that I am getting all the data types correct, I like to see what a sample response looks like.
 
The `index` on the `/text_sections/{text_section_id}/relationships/resource_collections` route looks like it is being used so I want to make sure I understand it. I looked around on the Minnesota press website to find example responses from that route, but every response was empty. 

I wanted to be able to create my own resource_collection on a text_section for my local version of manifold, but I can't seem to figure out how to do that. I presume there is some way to add a resource_collection to a text_section? Maybe that happens during ingestion of a text?

**Comment by zdavis** [comment]
#2518 will address the exception. Please be sure to fix the request spec you added so it actually asserts that it will get a 200 response with an expect statement.

**Comment by zdavis** [comment]
For the second issue, I'm pretty sure that text_sections/relationships/resource_collections is showing a text_section's resource collections via the `has_many :resource_collections, through: :annotations` so the client can load all referenced collections at once for a text section when it's viewed. Creating resource and resource collection annotations on a text section should give you what you want.

**Comment by zdavis** [comment]
We agreed that the #create and #index routes on resource collections will be removed. Remove corresponding specs for this and re-label as ready for review. Thanks.

**Comment by ConnorChristensen** [comment]
Both the issues I had when I started have been resolved.

* The rswag tests for #create and #index routes on resource_collections were removed
* The POST test I wrote in `/api/spec/requests/resource_collections_spec.rb` was removed
* I got a resource_collection attached to a text_section through the use of a annotation

**Pull request merged**
