### PR TITLE
[C] Refactor HasMany component

### PR DESCRIPTION
**Pull request by SMaxOwok**
This refactor breaks the `HasMany` form component into smaller sub-components.  Additionally, it introduces a new style when neither the `orderable` or `editClickHandler` props are passed through.

Will be necessary for project collection styles.

### CODE REVIEW

**Comment by SMaxOwok** [comment]
screen shot 2018-09-17 at 12 35 35 pm

**Comment by SMaxOwok** [comment]
subjects
tags

**Comment by zdavis** [comment]
Remove button is positioned a few pixels too high relative to the label:
image

**Comment by zdavis** [comment]
Seeing errors with a resource that already existed prior to pulling this branch (and did not have any tags):

image

**Comment by zdavis** [comment]
Need to change TagList prop validation to:
```
    value: PropTypes.oneOfType([PropTypes.string, PropTypes.array]),
```
(oneOfType instead of oneOf)

- Well should be min-height to size of one tag row.
- Improve vertical alignment in text input and in tag labels.

**Comment by SMaxOwok** [comment]
Added new empty states to the bucket style.
screen shot 2018-09-18 at 3 58 02 pm
screen shot 2018-09-18 at 3 58 10 pm

**Comment by zdavis** [comment]
A little concerned about code duplication between the list that the TagList produces and the non-orderable list that the HasMany produces. Asked Max to review and see if there are opportunities to reduce code repetition.

**Pull request merged**
