### PR TITLE
 [F] Add text section management to stylesheet edit

### PR DESCRIPTION
**Pull request by SMaxOwok**

### CODE REVIEW

**Comment by SMaxOwok** [comment]
screen shot 2018-09-24 at 2 40 05 pm

**Comment by SMaxOwok** [comment]
This is currently creating the association on select from the list.  Once #1408 is approved/merged, we can defer the associations to be handled on save.

**Comment by SMaxOwok** [comment]
well

**Comment by zdavis** [comment]
One last small change on this... the focus state on the add/remove links and on the pills needs a little improvement. 

image

**Comment by SMaxOwok** [comment]
@zdavis updated

**Comment by zdavis** [comment]
Please fix conflicts, then I will accept.

**Comment by SMaxOwok** [comment]
@zdavis updated

**Pull request merged**
