### PR TITLE
[B] Remove text transition on resource previews

### PR DESCRIPTION
**Pull request by naomiyaki**
[Fixes #143208159]

### CODE REVIEW

**Comment by SMaxOwok** [comment]
safari_resource

I'm seeing the resource icons not center aligned anymore in Safari.

**Comment by zdavis** [comment]
There was chat about this in slack, but I didn't follow the specifics. Is there more to be done here?

**Comment by zdavis** [comment]
Ping @naomiyaki @SMaxOwok

**Comment by SMaxOwok** [comment]
I didn't see anything else weird with it.  I wasn't able to check in IE though, so maybe someone wants to look there quickly.

**Pull request merged**
