### PR TITLE
[WIP] Document favorite_projects API route

### PR DESCRIPTION
**Pull request by ConnorChristensen**

### CODE REVIEW

**Comment by zdavis** [comment]
Rejecting this per our slack conversation
https://manifold-community.slack.com/archives/GNB3TD8P8/p1578597243003200

**Comment by zdavis** [comment]
This one's getting a little stale—see if you can address my feedback on it today.

**Comment by ConnorChristensen** [comment]
At the end of our slack conversation (https://manifold-community.slack.com/archives/GNB3TD8P8/p1578597243003200), it seemed that I'm not fully understanding how or where metadata attributes are attached to a serialized response and suggested I work on something else until you can give me more of a direction. I'm happy to have a quick chat about it, or get some pointers through slack or here in this PR.

I updated the branch so it is current again. If this metadata stuff is too complicated to deal with now, I can leave this for another time and make this PR just the commit that documents the favorite_project endpoint.

**Comment by zdavis** [comment]
I added changes to this. Can be merged once checks pass.

**Pull request merged**
