### PR TITLE
[B] Self-close void element tags in html validator

### PR DESCRIPTION
**Pull request by SMaxOwok**
The primary issue here was that the source html had unlcosed `<source>` tags.  While this is valid HTML 5, Nokogiri adds closing `</source>` tags, which is invalid.  Additionally, Nokogiri adds these closing tags in inconsistent places, resulting in some invalid nesting.

This fix adds a step in the HTML validator that will take void elements and ensure they're closed while maintaining their properties.  It will also remove any closing void tags.  It runs as the last step in the validator because we're manipulating the resulting HTML string, not the parsed nodes, and sending the string back through Nokogiri will add back the removed closing tags.

### CODE REVIEW

**Comment by zdavis** [comment]
Why not address all void tags in this?

https://developer.mozilla.org/en-US/docs/Glossary/Empty_element

**Comment by SMaxOwok** [comment]
@zdavis updated

**Comment by scryptmouse** [comment]
Rather than using regexes to correct void elements, we might consider using an HTML5 parser extension for nokogiri:

https://github.com/rubys/nokogumbo

**Comment by zdavis** [comment]
I like Alexa's suggestion. Max, can you take a look at that approach?

**Comment by zdavis** [comment]
I'm going to accept this PR in the meantime, however, but would like to explore the HTML5 parser.

**Pull request merged**
