### PR TITLE
[B] Fix drawer list items not truncating

### LINKED ISSUE #2052: Reader resource drawer scrolls horizontally with long titles
drawer

### PR DESCRIPTION
**Pull request by SMaxOwok**
Fixes #2052

### CODE REVIEW

**Comment by zdavis** [comment]
Can you say a few words about why/how this fix addresses the problem? It's not at all obvious why removing padding and adding min-width 0 is a solution.

**Comment by SMaxOwok** [comment]
@dananjohnson found the solution in the `.long-and-truncated-with-child-corrected` example from https://css-tricks.com/snippets/css/truncate-string-with-ellipsis/

**Comment by zdavis** [comment]
Cool. I'll leave this open so I can work it into my list refactor and then close it.

**Comment by SMaxOwok** [comment]
Will be fixed in #2075

**Pull request closed without merging**
