### PR TITLE
[F] Add validation to annotations model

### PR DESCRIPTION
**Pull request by SMaxOwok**
[Delivers #138731665]

### CODE REVIEW

**Comment by zdavis** [comment]
Rebase on dev and I'll accept.

**Comment by SMaxOwok** [comment]
Rebased on dev.  Not sure why it says there are conflicts... I can't find any.

**Comment by zdavis** [comment]
This pull request is against `mo/valid-annotations`, not against `development`. Can you submit the PR against dev?

**Comment by zdavis** [comment]
Actually, NM I can do it

**Pull request merged**
